Upload Migration Alignments
wetransform-os/xplanung-transformationswerkzeuge pull request #5
Opened 2022-10-06 12:07 UTC by Claudia-WE

2022-10-10 13:47 UTC, JohannaOtt requested changes
Changes to be done are documented in relevant tickets SVC-1230, SVC-1231 and SVC-1232

2022-10-28 12:02 UTC, JohannaOtt commented
@Claudia-WE I can see that some changes were directly pushed to the main branch and not added to this PR - for example in this folder https://github.com/wetransform-os/xplanung-transformationswerkzeuge/tree/main/Versionsmigration/5.0-5.4
Not sure if and how that can be properly reverted so that changes are added via a PR. Maybe you can have a look at this together with Florian.

2022-11-17 14:12 UTC, JohannaOtt requested changes

2022-11-17 14:12 UTC, JohannaOtt commented on Versionsmigration/5.2-5.4/xplangml-migration-52-54.halex
> +    <resource action-id="eu.esdihumboldt.hale.io.instance.read.source" provider-id="eu.esdihumboldt.hale.io.gml.reader">
I would vote for not committing source data loaded.

2022-11-17 14:12 UTC, JohannaOtt commented on Versionsmigration/5.0-5.4/xplangml-migration-50-54.halex
> +    <resource action-id="eu.esdihumboldt.hale.io.instance.read.source" provider-id="eu.esdihumboldt.hale.io.gml.reader">
Again, I would avoid to load data.

2022-11-18 13:36 UTC, Claudia-WE commented
Closing, created seperate pull requests for each alignment

2022-11-18 13:36 UTC, closed without merging